services:
  - type: web
    name: ipl-auction
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_i5SElZgYUuv4@ep-wandering-credit-am7kjfuw-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
